flask_intermediate/user_message_password_login/project/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired


class UserForm(FlaskForm):
    first_name = StringField("first_name", validators=[DataRequired()])
    last_name = StringField("last_name", validators=[DataRequired()])
    user_name = StringField("user_name", validators=[DataRequired()])
    password = PasswordField("password", validators=[DataRequired()])


class LoginForm(FlaskForm):
    user_name = StringField("user_name", validators=[DataRequired()])
    password = PasswordField("password", validators=[DataRequired()])

flask_intermediate/user_message_password_login/project/users/views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    flash,
    session,
    g,
)
from flask_wtf.csrf import validate_csrf, ValidationError
from project.users.forms import UserForm, LoginForm
from project.models import User
from project import db, bcrypt
from sqlalchemy.exc import IntegrityError
from project.decorators import (
    ensure_authenticated,
    prevent_double_login,
    ensure_correct_user,
)

users_blueprint = Blueprint("users", __name__, template_folder="templates")


@users_blueprint.before_request
def current_user():
    if session.get("user_id"):
        g.current_user = User.query.get(session["user_id"])
    else:
        g.current_user = None


@users_blueprint.route("/", methods=["GET"])
@ensure_authenticated
def index():
    return render_template("users/index.html", users=User.query.all())


@users_blueprint.route("/new", methods=["GET"])
@prevent_double_login
def new():
    form = UserForm()
    return render_template("users/new.html", form=form)


@users_blueprint.route("/", methods=["POST"])
@prevent_double_login
def new_user():
    form = UserForm(request.form)
    if form.validate():
        try:
            new_user = User(
                form.first_name.data,
                form.last_name.data,
                form.user_name.data,
                form.password.data,
            )
            db.session.add(new_user)
            db.session.commit()
            session["user_id"] = new_user.id
            flash("User Created!")
            return redirect(url_for("users.show", id=new_user.id))
        except IntegrityError:
            flash("Username already taken!")
    return render_template("users/new.html", form=form)


@users_blueprint.route("/login", methods=["GET"])
@prevent_double_login
def login():
    form = LoginForm()
    return render_template("users/login.html", form=form)


@users_blueprint.route("/login", methods=["POST"])
@prevent_double_login
def login_user():
    form = LoginForm(request.form)
    if form.validate():
        authenticated_user = User.authenticate(form.user_name.data, form.password.data)
        if authenticated_user:
            session["user_id"] = authenticated_user.id
            return redirect(url_for("users.show", id=authenticated_user.id))
        else:
            flash("Invalid Credentials!")
    return render_template("users/login.html", form=form)


@users_blueprint.route("/<int:id>", methods=["GET"])
@ensure_authenticated
def show(id):
    user = User.query.get(id)
    if not user:
        return render_template("404.html")
    return render_template("users/show.html", user=user, messages=user.messages)


@users_blueprint.route("/<int:id>/edit", methods=["GET"])
@ensure_authenticated
@ensure_correct_user
def edit(id):
    user = User.query.get(id)
    if not user:
        return render_template("404.html")
    form = UserForm(obj=user)
    return render_template("users/edit.html", form=form, user=user)


@users_blueprint.route("/<int:id>", methods=["PATCH"])
@ensure_authenticated
@ensure_correct_user
def edit_user(id):
    form = UserForm(request.form)
    if form.validate():
        user = User.query.get(id)
        user.first_name = request.form["first_name"]
        user.last_name = request.form["last_name"]
        db.session.add(user)
        db.session.commit()
        return redirect(url_for("users.index"))
    return render_template("users/show.html", user=user)


@users_blueprint.route("/<int:id>", methods=["DELETE"])
@ensure_authenticated
@ensure_correct_user
def delete(id):
    try:
        validate_csrf(request.form.get("csrf_token"))
        user = User.query.get(id)
        for message in user.messages:
            db.session.delete(message)
        db.session.delete(user)
        db.session.commit()
        return redirect(url_for("users.index"))
    except ValidationError:
        return redirect(url_for("users.index"))


@users_blueprint.route("/logout", methods=["GET"])
@ensure_authenticated
def logout():
    session.pop("user_id")
    flash("Logged out!")
    return redirect(url_for("users.login"))

flask_intermediate/user_message_password_login/project/users/templates/users/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('users.edit_user', id=user.id)}}?_method=PATCH">
  {{ form.csrf_token }}
  <p>
    {{ form.first_name(placeholder="First Name") }}
    <span>
      {% if form.first_name.errors %}
        {% for error in form.first_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.last_name(placeholder="Last Name") }}
    <span>
      {% if form.last_name.errors %}
        {% for error in form.last_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Edit</button>
</form>
<form action="{{ url_for('users.show', id=user.id) }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/users/templates/users/index.html
{% extends 'base.html' %}
{% block content %}
<h2>You're logged in as {{ g.current_user.first_name  }} {{ g.current_user.last_name }}</h2>
{% for user in users %}
    <p>
      <a href="{{ url_for('users.show', id=user.id) }}"
      style="text-decoration: none;color: black;">
      {{ user.first_name }} {{ user.last_name }}
      </a>
      <br>
    </p>
{% endfor %}
    <form action="{{ url_for('messages.index') }}" method="GET">
        <input type="submit" value="Messages">
    </form>
    <form action="{{ url_for('tags.index') }}" method="GET">
        <input type="submit" value="Tags">
    </form>
    <form action="{{ url_for('users.logout') }}" method="GET">
        <input type="submit" value="Sign out">
    </form>
{% endblock %}

flask_intermediate/user_message_password_login/project/users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('users.login_user')}}">
    {{ form.csrf_token }}

    {{ form.user_name(placeholder="User Name") }}
    <span>
      {% if form.user_name.errors %}
        {% for error in form.user_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.password(placeholder="Password") }}
    <span>
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Sign In</button>
</form>
<form action="{{ url_for('messages.index') }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/users/templates/users/new.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('users.new_user')}}">
    {{ form.csrf_token }}
  <p>
    {{ form.first_name(placeholder="First Name") }}
    <span>
      {% if form.first_name.errors %}
        {% for error in form.first_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.last_name(placeholder="Last Name") }}
    <span>
      {% if form.last_name.errors %}
        {% for error in form.last_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.user_name(placeholder="User Name") }}
    <span>
      {% if form.user_name.errors %}
        {% for error in form.user_name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.password(placeholder="Password") }}
    <span>
      {% if form.password.errors %}
        {% for error in form.password.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Sign Up</button>
</form>
<form action="{{ url_for('messages.index') }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/users/templates/users/show.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ user.first_name }} {{ user.last_name }}</h1>
    <ul>
        {% for message in messages %}
        <li>
          <a
            href="{{ url_for('messages.show', id=message.id) }}"
            style="text-decoration: none;color: black;"
          >
            {{ message.message }}
          </a>
        </li>
        {% endfor %}
    </ul>
    {% if g.current_user == user %}
    <form action="{{ url_for('messages.new', user_id=user.id) }}" method="GET">
        <input type="submit" value="New Message">
    </form>
    <form action="{{ url_for('users.edit', id=user.id) }}" method="GET">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="submit" value="Change Name">    
    </form>
    <form action="{{ url_for('users.logout') }}" method="GET">
        <input type="submit" value="Sign Out">
    </form>
    <form action="{{ url_for('users.delete', id=user.id) }}?_method=DELETE" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="submit" value="Delete Account">
    </form>
    {% endif %}
    <form action="{{ url_for('users.index') }}" method="GET">
        <input type="submit" value="Users">
    </form>
    <form action="{{ url_for('messages.index') }}" method="GET">
        <input type="submit" value="Messages">
    </form>
    <form action="{{ url_for('tags.index') }}" method="GET">
        <input type="submit" value="Tags">
    </form>
    {% endblock %}
    