flask_intermediate/user_message_password_login/project/tags/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectMultipleField, widgets
from wtforms.validators import DataRequired
from project.models import Message


class TagForm(FlaskForm):
    tag = StringField("tag", validators=[DataRequired()])
    messages = SelectMultipleField(
        "messages",
        coerce=int,
        widget=widgets.ListWidget(prefix_label=False),
        option_widget=widgets.CheckboxInput(),
    )

    def set_choices(self):
        self.messages.choices = [(m.id, m.message) for m in Message.query.all()]

flask_intermediate/user_message_password_login/project/tags/views.py
from flask import Blueprint, render_template, redirect, url_for, request
from flask_wtf.csrf import validate_csrf, ValidationError
from project.tags.forms import TagForm
from project.models import Tag, Message
from project import db

tags_blueprint = Blueprint("tags", __name__, template_folder="templates")


@tags_blueprint.route("/", methods=["GET"])
def index():
    return render_template("tags/index.html", tags=Tag.query.all())


@tags_blueprint.route("/new", methods=["GET"])
def new():
    form = TagForm()
    form.set_choices()
    return render_template("tags/new.html", form=form)


@tags_blueprint.route("/", methods=["POST"])
def new_tag():
    form = TagForm(request.form)
    form.set_choices()
    if form.validate():
        tag = Tag(request.form["tag"])
        messages = [Message.query.get(m) for m in form.messages.data]
        tag.messages.extend(messages)
        db.session.add(tag)
        db.session.commit()
        return redirect(url_for("tags.index"))
    return render_template("tags/new.html", form=form)


@tags_blueprint.route("/<int:id>", methods=["GET"])
def show(id):
    tag = Tag.query.get(id)
    if not tag:
        return render_template("404.html")
    return render_template("tags/show.html", tag=tag)


@tags_blueprint.route("/<int:id>/edit", methods=["GET"])
def edit(id):
    tag = Tag.query.get(id)
    if not tag:
        return render_template("404.html")
    messages = [m.id for m in tag.messages]
    form = TagForm(obj=tag)
    form.set_choices()
    form.messages.process_data(messages)
    return render_template("tags/edit.html", form=form, tag=tag)


@tags_blueprint.route("/<int:id>", methods=["PATCH"])
def edit_tag(id):
    form = TagForm(request.form)
    form.set_choices()
    if form.validate():
        tag = Tag.query.get(id)
        tag.tag = request.form["tag"]
        tag.messages = [Message.query.get(m) for m in form.messages.data]
        db.session.add(tag)
        db.session.commit()
    return redirect(url_for("tags.index"))


@tags_blueprint.route("/<int:id>", methods=["DELETE"])
def delete(id):
    try:
        validate_csrf(request.form.get("csrf_token"))
        tag = Tag.query.get(id)
        db.session.delete(tag)
        db.session.commit()
        return redirect(url_for("tags.index"))
    except ValidationError:
        return redirect(url_for("tags.index"))

flask_intermediate/user_message_password_login/project/tags/templates/tags/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('tags.edit_tag', id=tag.id)}}?_method=PATCH">
  {{ form.csrf_token }}
  <p>
    {{ form.tag(placeholder="Tag") }}
    <span>
      {% if form.tag.errors %}
        {% for error in form.tag.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {{ form.messages }}
  <button type="submit">Edit</button>
</form>
<form action="{{ url_for('tags.show', id=tag.id) }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/tags/templates/tags/index.html
{% extends 'base.html' %}
{% block content %}
{% for tag in tags %}
    <p>
      <a href="{{ url_for('tags.show', id=tag.id) }}"
      style="text-decoration: none;color: black;">
      {{ tag.tag }} 
      </a>
      <br>
    </p>
{% endfor %}
<form action="{{ url_for('tags.new') }}" method="GET">
  <input type="submit" value="New Tag">
</form>
<form action="{{ url_for('users.index') }}" method="GET">
  <input type="submit" value="Users">
</form>
<form action="{{ url_for('messages.index') }}" method="GET">
  <input type="submit" value="Messages">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/tags/templates/tags/new.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('tags.new_tag')}}">
    {{ form.csrf_token }}
  <p>
    {{ form.tag(placeholder="Tag") }}
    <span>
      {% if form.tag.errors %}
        {% for error in form.tag.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  {{ form.messages }}
  <button type="submit">Add Tag</button>
</form>
<form action="{{ url_for('tags.index') }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/tags/templates/tags/show.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ tag.tag }}</h1>
    {% for message in tag.messages %}
    <p>
        <a href="{{ url_for('messages.show', id=message.id) }}"
        style="text-decoration: none;color: black;">
        {{ message.message }}
    </a>
    <br>
</p>
{% endfor %}
<form action="{{ url_for('tags.delete', id=tag.id) }}?_method=DELETE" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <input type="submit" value="X" style="color: red;">
</form>
<form action="{{ url_for('tags.edit', id=tag.id) }}" method="GET">
  <input type="submit" value="Edit">
</form>
<form action="{{ url_for('users.index') }}" method="GET">
  <input type="submit" value="Users">
</form>
<form action="{{ url_for('messages.index') }}" method="GET">
  <input type="submit" value="Messages">
</form>
<form action="{{ url_for('tags.index') }}" method="GET">
  <input type="submit" value="Tags">
</form>
{% endblock %}