flask_intermediate/user_message_password_login/project/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectMultipleField, widgets
from wtforms.validators import DataRequired
from project.models import Tag


class MessageForm(FlaskForm):
    message = StringField("message", validators=[DataRequired()])
    tags = SelectMultipleField(
        "Tags",
        coerce=int,
        widget=widgets.ListWidget(prefix_label=False),
        option_widget=widgets.CheckboxInput(),
    )
    new_tag = StringField("new_tag")

    def set_choices(self):
        self.tags.choices = [(t.id, t.tag) for t in Tag.query.all()]

flask_intermediate/user_message_password_login/project/messages/views.py
from flask import Blueprint, render_template, redirect, url_for, request, g, session
from flask_wtf.csrf import validate_csrf, ValidationError
from project.messages.forms import MessageForm
from project.models import Message, User, Tag
from project import db
from project.decorators import (
    ensure_authenticated,
    ensure_correct_user,
    ensure_correct_user_edit_delete,
)

messages_blueprint = Blueprint("messages", __name__, template_folder="templates")


@messages_blueprint.before_request
def current_user():
    if session.get("user_id"):
        g.current_user = User.query.get(session["user_id"])
    else:
        g.current_user = None


@messages_blueprint.route("/", methods=["GET"])
def index():
    messages = Message.query.all()
    return render_template("messages/index.html", messages=messages)


@messages_blueprint.route("/new/<int:user_id>", methods=["GET"])
@ensure_authenticated
@ensure_correct_user
def new(user_id):
    if not User.query.get(user_id):
        return render_template("404.html")
    form = MessageForm()
    form.set_choices()
    return render_template("messages/new.html", user_id=user_id, form=form)


@messages_blueprint.route("/<int:user_id>", methods=["POST"])
@ensure_authenticated
@ensure_correct_user
def new_message(user_id):
    form = MessageForm(request.form)
    form.set_choices()
    if form.validate():
        user = User.query.get(user_id)
        message = Message(request.form["message"])
        tags = [Tag.query.get(t) for t in form.tags.data]
        new_tag = get_new_tag(request.form["new_tag"])
        if new_tag:
            tags.append(new_tag)
        message.tags.extend(tags)
        user.messages.extend([message])
        db.session.commit()
    return redirect(url_for("messages.index"))


def get_new_tag(new_tag):
    if new_tag:
        tag = Tag(new_tag)
        db.session.add(tag)
        db.session.commit()
        return tag


@messages_blueprint.route("/<int:id>", methods=["GET"])
@ensure_authenticated
def show(id):
    message = Message.query.get(id)
    if not message:
        return render_template("404.html")
    return render_template("messages/show.html", message=message)


@messages_blueprint.route("/<int:id>/edit", methods=["GET"])
@ensure_authenticated
@ensure_correct_user_edit_delete
def edit(id):
    message = Message.query.get(id)
    if not message:
        return render_template("404.html")
    tags = [t.id for t in message.tags]
    form = MessageForm(obj=message)
    form.set_choices()
    form.tags.process_data(tags)
    return render_template("messages/edit.html", form=form, message=message)


@messages_blueprint.route("/<int:id>", methods=["PATCH"])
@ensure_authenticated
@ensure_correct_user_edit_delete
def edit_message(id):
    form = MessageForm(request.form)
    form.set_choices()
    if form.validate():
        message = Message.query.get(id)
        message.message = request.form["message"]
        message.tags = [Tag.query.get(t) for t in form.tags.data]
        new_tag = get_new_tag(request.form["new_tag"])
        if new_tag:
            message.tags.append(new_tag)
        db.session.add(message)
        db.session.commit()
    return redirect(url_for("messages.index"))


@messages_blueprint.route("/<int:id>", methods=["DELETE"])
@ensure_authenticated
@ensure_correct_user_edit_delete
def delete(id):
    try:
        validate_csrf(request.form.get("csrf_token"))
        db.session.delete(Message.query.get(id))
        db.session.commit()
        return redirect(url_for("messages.index"))
    except ValidationError:
        return redirect(url_for("messages.index"))

flask_intermediate/user_message_password_login/project/messages/templates/messages/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('messages.edit_message', id=message.id)}}?_method=PATCH">
  {{ form.csrf_token }}
  <p>
    {{ form.message(placeholder="Message") }}
    <span>
      {% if form.message.errors %}
        {% for error in form.message.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.tags }}
  </p>
  <p>
    {{ form.new_tag(placeholder="New Tag") }}
    <span>
      {% if form.new_tag.errors %}
        {% for error in form.new_tag.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Edit</button>
</form>
<form action="{{ url_for('users.show', id=message.users[0].id) }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/messages/templates/messages/index.html
{% extends 'base.html' %} {% block content %}
<h1>Messages from People</h1>
<ul>
  {% for message in messages %}
  <li>
    <a
      href="{{ url_for('messages.show', id=message.id) }}"
      style="text-decoration: none;color: black;"
    >
      {{ message.message }}
    </a>
    ---
    <a
      href="{{ url_for('users.show', id=message.users[0].id) }}"
      style="text-decoration: none;color: black;"
    >
      {{ message.users[0].first_name }} {{ message.users[0].last_name }}
    </a>
  </li>
  {% endfor %}
</ul>
{% if not g.current_user %}
<form action="{{ url_for('users.login') }}">
  <input type="submit" value="Sign In" />
</form>
<form action="{{ url_for('users.new') }}">
  <input type="submit" value="Sign Up" />
</form>
{% else %}
<form action="{{ url_for('users.index') }}">
  <input type="submit" value="Users" />
</form>
<form action="{{ url_for('tags.index') }}">
  <input type="submit" value="Tags" />
</form>
{% endif %}
{% endblock %}

flask_intermediate/user_message_password_login/project/messages/templates/messages/new.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('messages.new_message', user_id=user_id)}}">
    {{ form.csrf_token }}
  <p>
    {{ form.message(placeholder="New Message") }}
    <span>
      {% if form.message.errors %}
        {% for error in form.message.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <p>
    {{ form.tags }}
  </p>
  <p>
    {{ form.new_tag(placeholder="New Tag") }}
    <span>
      {% if form.new_tag.errors %}
        {% for error in form.new_tag.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Add message</button>
</form>
<form action="{{ url_for('messages.index') }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/user_message_password_login/project/messages/templates/messages/show.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ message.message }}</h1>
    {% for tag in message.tags %}
    <ul>
        <li>
            {{ tag.tag }}
        </li>
    </ul>
    {% endfor%}
    {% if g.current_user == message.users[0] %}
    <form action="{{ url_for('messages.edit', id=message.id) }}">
        <input type="submit" name="edit_message" id="edit_message_btn" value="Edit">
    </form>
    <form action="{{ url_for('messages.delete', id=message.id) }}?_method=DELETE" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <input type="submit" name="del_message" id="del_message_btn"
        value="X" style="color: red;">
    </form>
    {% endif %}
    <form action="{{ url_for('users.index') }}" method="GET">
        <input type="submit" value="Users">
    </form>
    <form action="{{ url_for('messages.index') }}" method="GET">
        <input type="submit" value="Messages">
    </form>
    <form action="{{ url_for('tags.index') }}" method="GET">
        <input type="submit" value="Tags">
    </form>
{% endblock %}