flask_intermediate/many_to_many/project/departments/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField
from wtforms.validators import DataRequired
from project.models import Department

class NewDepartmentForm(FlaskForm):
    name = TextField("Name", validators=[DataRequired()])

flask_intermediate/many_to_many/project/departments/views.py
from flask import Blueprint, redirect, render_template, request, url_for
from flask_wtf.csrf import validate_csrf, ValidationError
from project.departments.forms import NewDepartmentForm
from project.models import Department
from project import db

departments_blueprint = Blueprint("departments", __name__, template_folder="templates")


@departments_blueprint.route("/", methods=["GET"])
def index():
    return render_template("departments/index.html", departments=Department.query.all())


@departments_blueprint.route("/new", methods=["GET"])
def new():
    return render_template("departments/new.html", form=NewDepartmentForm())


@departments_blueprint.route("/", methods=["POST"])
def new_department():
    form = NewDepartmentForm(request.form)
    if form.validate():
        department = Department(request.form["name"])
        db.session.add(department)
        db.session.commit()
        return redirect(url_for("departments.index"))
    return redirect(url_for("departments.new"))


@departments_blueprint.route("/<int:id>", methods=["GET"])
def show(id):
    department = Department.query.get(id)
    if not department:
        return render_template("404.html")
    return render_template(
        "departments/show.html", department=department, employees=department.employees
    )


@departments_blueprint.route("/<int:id>", methods=["DELETE"])
def delete(id):
    try:
        validate_csrf(request.form.get("csrf_token"))
        db.session.delete(Department.query.get(id))
        db.session.commit()
    except ValidationError:
        pass
    finally:
        return redirect(url_for("departments.index"))


@departments_blueprint.route("/<int:id>/edit", methods=["GET"])
def edit(id):
    department = Department.query.get(id)
    if not department:
        return render_template("404.html")
    form = NewDepartmentForm(obj=department)
    return render_template("departments/edit.html", form=form, department=department)


@departments_blueprint.route("/<int:id>/edit", methods=["PATCH"])
def edit_department(id):
    form = NewDepartmentForm(request.form)
    if form.validate():
        department = Department.query.get(id)
        department.name = request.form["name"]
        db.session.commit()
    return redirect(url_for("departments.index"))

flask_intermediate/many_to_many/project/departments/templates/departments/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('departments.edit_department', id=department.id)}}?_method=PATCH">
        {{ form.csrf_token }}
      <p>
          <p>
              {{ form.name.label}}:
          </p>
        {{ form.name(placeholder="Name") }}
        <span>
          {% if form.name.errors %}
            {% for error in form.name.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
        </span>
      </p>
      <button type="submit">Edit department</button>
    </form>
    <form action="{{ url_for('departments.index') }}" method="GET">
        <input type="submit" value="Cancel">
    </form>
{% endblock %}

flask_intermediate/many_to_many/project/departments/templates/departments/index.html
{% extends 'base.html' %}
{% block content %}
{% for department in departments %}
    <p>
        {{ department.name }}:
        {% for e in department.employees %}
        <p>
            {{ e.name }}
        </p>
        {% endfor %}
      <br>
    </p>
{% endfor %}
{% endblock %}

flask_intermediate/many_to_many/project/departments/templates/departments/new.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="{{url_for('departments.new_department')}}">
    {{ form.csrf_token }}
  <p>
    {{ form.name(placeholder="Name") }}
    <span>
      {% if form.name.errors %}
        {% for error in form.name.errors %}
          {{ error }}
        {% endfor %}
      {% endif %}
    </span>
  </p>
  <button type="submit">Add Department</button>
</form>
<form action="{{ url_for('departments.index') }}" method="GET">
    <input type="submit" value="Cancel">
</form>
{% endblock %}

flask_intermediate/many_to_many/project/departments/templates/departments/show.html
{% extends 'base.html' %}
{% block content %}
    <h1>{{ department.name }}</h1>
    {% for employee in employees %}
        <p>
            {{ employee.name }}
        </p>
    {% endfor %}
    <form action="{{ url_for('departments.delete', id=department.id) }}?_method=DELETE" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input type="submit" value="Delete Department">
    </form>
{% endblock %}